### ISSUE TITLE
exclusions does not work

### ISSUE THREAD

**Issue by cdcseacave** [WebFreak001/deploy-nightly#19]
I've tried both `exclusions` and `recursive_exclusions` and all files are added to the archive; what am I doing wrong?
```
      - name: Zip Windows release
        if: matrix.os == 'windows-latest'
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          directory: ${{ github.workspace }}/make/bin/
          recursive_exclusions: '*.exp'
          filename: 'OpenMVS_Windows.zip'
```
