### ISSUE TITLE
Unable to use action, fails with "Error: Not Found"

### ISSUE THREAD

**Issue by mwestphal** [WebFreak001/deploy-nightly#20]
I'm trying to use this action to publish a nightly, it fails with

```
    - name: Deploy Ubuntu release
      if: matrix.os == 'ubuntu-latest'
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: "https://uploads.github.com/repos/f3d-app/f3d-superbuild/releases/85470861/assets{?name,label}"
        release_id: 85470861
        asset_path: ./build/CMakeCache.txt
        asset_name: CMakeCache.txt
        asset_content_type: text/plain
        max_releases: 7
```

```
Run WebFreak001/deploy-nightly@v1.1.0
/usr/bin/docker exec  ce715c73b0211a65e429b2eb5d5e3f7b21b446ac92d331fa53b0af8969c7aac4 sh -c "cat /etc/*release | grep ^ID"
Checking previous assets
Error: Not Found
```
