### ISSUE TITLE
Release to public repo from private repo

### ISSUE THREAD

**Issue by fgregg** [WebFreak001/deploy-nightly#26]
Thanks for this great resource. I have a private repo and i'm trying to use deploy-nightly to release an artifact to a public repo's release.

Is it possible to do this. I'm getting a bit of an obscure error message.

snippet from github action
```yaml
    - name: Deploy Windows release
      uses: WebFreak001/deploy-nightly@v3.0.0
      with:
        repo: labordata/warehouse
        upload_url: https://uploads.github.com/repos/labordata/warehouse/releases/134114950/assets{?name,label}
        release_id: 134114950 # same as above (id can just be taken out the upload_url, it's used to find old releases)
        asset_path: ./new_postings.csv # path to archive to upload
        asset_name: new_postings.csv # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
        asset_content_type: text/csv # required by GitHub API
```

output from github actions.

```console
Run WebFreak001/deploy-nightly@v3.0.0
  with:
    repo: labordata/warehouse
    upload_url: [https://uploads.github.com/repos/labordata/warehouse/releases/134114950/assets{?name,label}](https://uploads.github.com/repos/labordata/warehouse/releases/134114950/assets%7B?name,label})
    release_id: 134114950
    asset_path: ./new_postings.csv
    asset_name: new_postings.csv
    asset_content_type: text/csv
    max_releases: 7
    token: ***
    sha: 54851d57f7522284daae85c51e443ca191112eb1
Checking previous assets
Uploading asset as file new_postings.csv
Error: Resource not accessible by integration
```

**Comment by WebFreak001** [comment]
the default generated github token may not have the necessary permissions to upload to a different repo, generate a token that has access to your other repository and paste the token into the github secrets. Then in the action, set `token` to the secret you added to github.

**Comment by fgregg** [comment]
i create a fine-grained token that had write permissions on releases in the target repo, and used that token in the github action

<img width="811" alt="Screenshot 2023-12-16 at 2 11 40 PM" src="https://github.com/WebFreak001/deploy-nightly/assets/536941/31b8d340-f784-4d86-83b2-1e66e85ff591">

```yaml
    - name: Deploy Windows release
      uses: WebFreak001/deploy-nightly@v3.0.0
      with:
        repo: labordata/warehouse
        token: ${secrets.WRITE_TO_WAREHOUSE_TOKEN}
        upload_url: https://uploads.github.com/repos/labordata/warehouse/releases/134114950/assets{?name,label}
        release_id: 134114950 # same as above (id can just be taken out the upload_url, it's used to find old releases)
        asset_path: ./new_postings.csv # path to archive to upload
        asset_name: new_postings.csv # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
        asset_content_type: text/csv # required by GitHub API
```
and i'm now getting a Bad Credentials Error

```console
Run WebFreak001/deploy-nightly@v3.0.0
  with:
    repo: labordata/warehouse
    token: ${secrets.WRITE_TO_WAREHOUSE_TOKEN}
    upload_url: [https://uploads.github.com/repos/labordata/warehouse/releases/134114950/assets{?name,label}](https://uploads.github.com/repos/labordata/warehouse/releases/134114950/assets%7B?name,label})
    release_id: 134114950
    asset_path: ./new_postings.csv
    asset_name: new_postings.csv
    asset_content_type: text/csv
    max_releases: 7
    sha: 8dac687a862e4d61214fc1367910ac5f48cee56a
Checking previous assets
Error: Bad credentials
```

are there other permissions i need for this?
